services:
  - type: web
    name: waqfenau-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:80
      - key: ConnectionStrings__DefaultConnection
        value: Host=ep-polished-hill-a6374v0f-pooler.us-west-2.aws.neon.tech;Database=neondb;Username=neondb_owner;Password=npg_jLJs8z6YqpuO;SSL Mode=Require;Trust Server Certificate=true
      - key: Jwt__Key
        value: WaqfENauSuperSecretKey2026ForAhmadiyyaNigeria@@
      - key: Jwt__Issuer
        value: WaqfENauApi
      - key: Jwt__Audience
        value: WaqfENauClient
      - key: Email__From
        value: noreply@waqfenau.org
      - key: Email__SmtpHost
        value: smtp.gmail.com
      - key: Email__SmtpPort
        value: "587"
      - key: Email__Username
        value: babshakeem786@gmail.com
      - key: Email__Password
        value: cdmt wrco thra awbc
